apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: ${env.KEYCLOAK_NAME:=keycloak}
  namespace: ${env.KEYCLOAK_NS:=keycloak}
spec:
  instances: 1
  db:
    vendor: postgres
    host: ${env.PSQL_SVC}.${env.PSQL_NS}.svc.cluster.local
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  ingress:
    className: openshift-default
  proxy:
    headers: xforwarded